### ISSUE TITLE
Recommonmark 0.5 with python3.7 and sphinx 3.0.0+

### ISSUE THREAD

**Issue by mgyong** [readthedocs/recommonmark#159]
When i tried to generate html
`make html`
Encountering issue with recommonmark/parser.py
Recommonmark 0.5 with python3.7 and sphinx 3.0.0+

**AttributeError: 'NoneType' object has no attribute 'append'**

```
# Sphinx version: 3.0.0+
# Python version: 3.7.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   24 added, 0 changed, 0 removed
#   reading sources... [  4%] basics
#   reading sources... [  8%] calculator
#   reading sources... [ 12%] executors
#   reading sources... [ 16%] facedetector
#   reading sources... [ 20%] frameworkarchitecture
#   reading sources... [ 25%] frameworkconcepts
#   reading sources... [ 29%] getstarted
#   reading sources... [ 33%] gpu
#   reading sources... [ 37%] hairsegmentation
# Loaded extensions:
#   sphinx.ext.mathjax (3.0.0+) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.1) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/alabaster/__init__.py
#   recommonmark (0.5.0) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/recommonmark/__init__.py
#   sphinx.ext.autodoc (3.0.0+) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (3.0.0+) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (3.0.0+) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (3.0.0+) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (3.0.0+) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.ifconfig (3.0.0+) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.viewcode (3.0.0+) from /Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/viewcode.py
Traceback (most recent call last):
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/application.py", line 340, in build
    self.builder.build_update()
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 332, in build
    updated_docnames = set(self.read())
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 438, in read
    self._read_serial(docnames)
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 460, in _read_serial
    self.read_doc(docname)
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 504, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/io.py", line 223, in read_doc
    pub.publish()
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/sphinx/io.py", line 109, in read
    self.parse()
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/recommonmark/parser.py", line 38, in parse
    self.convert_ast(ast)
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/recommonmark/parser.py", line 49, in convert_ast
    fn(node)
  File "/Users/mgyong/anaconda3/envs/py37/lib/python3.7/site-packages/recommonmark/parser.py", line 115, in visit_paragraph
    self.current_node.append(p)
AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by ppwwyyxx** [comment]
I met the same bug and here is a repro:
```python
from recommonmark.parser import CommonMarkParser
from docutils.utils import new_document
doc = new_document("abcd")

parser = CommonMarkParser()

inputstring = open('a.md').read()

parser.parse(inputstring, doc)
```
where "a.md" has the following content:

[a.txt](https://github.com/readthedocs/recommonmark/files/4173859/a.txt)

The above code works in recommonmark==0.4, but not in 0.5
